from __future__ import annotations

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

TEXTS = [
    "Trois ans plus tôt, un virus plonge le monde dans le chaos et transforme des millions d'humains en zombies.",
    "En pleine apocalypse, Shu est trahi par un ami, puis abandonné aux mâchoires des morts-vivants.",
    "Mais au seuil de la mort, un système mystérieux le renvoie dix minutes avant le début de la pandémie.",
    "Avec ses souvenirs du futur et un pouvoir capable d'évoluer, Shu ne compte plus seulement survivre.",
    "Cette fois, il changera son destin et fera payer chaque traître.",
    "Avant la suite, pensez à vous abonner et à laisser un petit like. Ça soutient énormément la chaîne.",
    "Revenons trois ans plus tôt, lorsqu'une météorite mystérieuse frappe la Terre et déclenche une crise sans précédent.",
    "En quelques mois, le virus transforme les populations et envahit la planète de zombies.",
    "La civilisation s'effondre. Au milieu du chaos, les derniers humains luttent désespérément pour rester en vie.",
    "Désormais, survivre est la seule loi. Sur un hôpital abandonné, un groupe prépare sa fuite en hélicoptère.",
    "Pendant le chargement, certains surveillent les alentours tandis que les autres entassent les dernières provisions.",
    "Mais derrière eux, une porte verrouillée commence déjà à céder sous les coups.",
    "Arme en main, Shu les avertit : cette porte ne tiendra plus très longtemps.",
    "Trop tard. Les zombies défoncent l'entrée et chargent, les yeux rouges et la gueule hurlante.",
    "Shu ordonne alors d'abandonner les provisions et de courir.",
    "Il pousse les derniers survivants vers l'hélicoptère et leur crie de décoller.",
    "Mais au moment de monter, une balle le frappe dans le dos.",
    "Il s'écroule, blessé et stupéfait, puis cherche fébrilement l'auteur du tir.",
    "Face à lui se tient Kawakita, pistolet levé et œil rougeoyant. Shu exige une explication.",
    "Kawakita l'accuse d'être trop puissant : tant que Shu vivra, lui ne pourra jamais diriger le groupe.",
    "Il convoite le commandement, mais avec Shu dans les parages, il restera éternellement un simple subordonné.",
    "Une seconde balle frappe Shu en pleine poitrine. Derrière lui, la horde approche déjà.",
    "Depuis l'hélicoptère, Kawakita ricane : dans ce monde, seul celui qui survit mérite la victoire.",
    "Dévoré par la horde, Shu jure que dans une autre vie, il enterrera Kawakita de ses propres mains.",
    "Soudain, un système s'active et renvoie son hôte dix minutes avant le commencement de l'apocalypse.",
    "Shu ouvre brusquement les yeux, encore complètement désorienté.",
    "Peu à peu, il reconnaît le plafond qui se trouve au-dessus de lui.",
    "Il se redresse sur un lit et découvre, stupéfait, l'infirmerie de son école.",
    "Il examine son corps, incapable de savoir s'il vit la réalité ou un simple rêve.",
    "C'est alors qu'une fenêtre translucide apparaît devant lui avec une notification du système.",
    "Désormais, chaque zombie vaincu pourra lâcher une capacité. Une fois équipée, elle augmentera directement sa puissance de combat.",
    "Ces capacités seront classées selon plusieurs niveaux de rareté.",
    "Gris, blanc, vert, bleu, violet, or, puis rouge : chaque couleur annonce un pouvoir supérieur.",
    "En éliminant des zombies, Shu gagnera aussi de l'expérience. Chaque niveau augmentera son nombre de capacités équipables.",
    "Pour l'instant, il est niveau un et ne peut en équiper que deux.",
    "Plus aucun doute : ce n'est pas un rêve. Shu vient réellement de revenir dans le passé.",
    "Et dans cette nouvelle vie, jamais il ne pardonnera à Kawakita.",
    "Un regard à l'horloge lui apprend qu'il reste trente-huit minutes avant la pandémie.",
    "Sa première priorité est donc simple : récupérer une arme.",
    "Il bondit du lit et rassemble rapidement tous ses souvenirs du futur.",
    "Dans son ancienne vie, le directeur avait utilisé un pistolet pour prendre le contrôle de l'école dès le début.",
    "Il s'entourait d'étudiantes et livrait même aux zombies tous ceux qui osaient lui résister.",
    "À cause de ce monstre, l'école était devenue un véritable enfer.",
    "Shu décide donc de régler son compte à ce salaud avant tout le monde.",
    "Devant le bureau, il entend le directeur proposer à une élève ses notes, une recommandation et une bourse contre ses faveurs.",
    "Le directeur lui demande froidement si elle a enfin pris sa décision.",
    "Elle refuse net : elle préfère quitter l'école plutôt que devenir sa maîtresse.",
    "Furieux d'être rejeté, l'homme la gifle et lui hurle de ne plus jamais lui répondre ainsi.",
    "Selon lui, elle devrait être reconnaissante qu'un homme aussi généreux daigne seulement s'intéresser à elle.",
    "Il avance tandis qu'elle le supplie de reculer. Pour lui, elle n'aurait qu'à se soumettre.",
    "C'est précisément à cet instant que Shu défonce la porte.",
    "Interrompu, le directeur lui hurle de partir et prétend être occupé.",
    "Shu se moque ouvertement de lui : même un déchet pareil peut donc diriger une école ?",
    "Le directeur menace de le faire expulser s'il ne retourne pas immédiatement en classe.",
    "La réponse de Shu tient en un coup de poing magistral.",
    "Debout au-dessus de lui, Shu exige de savoir où il cache son arme.",
    "Les yeux du directeur s'écarquillent. Comment ce garçon peut-il connaître son secret ?",
    "Le visage en sang, il nie pourtant posséder le moindre pistolet.",
    "Shu fixe alors une étagère et lui demande si l'arme se trouve dedans.",
    "Pris de panique, le directeur tend la main et le supplie de ne pas l'ouvrir.",
    "Shu lui écrase le bras sans lui laisser la moindre chance d'intervenir.",
    "Puis il fouille l'étagère jusqu'à retrouver exactement ce qu'il cherchait.",
    "Enfin, le pistolet est entre ses mains.",
    "À ce moment, deux agents de sécurité accourent pour secourir le directeur.",
    "Profitant de leur présence, celui-ci prétend que Shu l'a agressé avant de voler son arme.",
    "Il leur ordonne de le maîtriser, quitte à lui briser les jambes.",
    "Mais l'un des gardes panique en voyant qu'il s'agit d'une véritable arme.",
    "Le directeur tente de les rassurer : impossible, selon lui, qu'un vrai pistolet soit caché dans une école.",
    "Il insiste pourtant : ils doivent neutraliser Shu, même s'il faut le tuer.",
    "Un garde hésite encore et demande si l'arme est vraiment fausse.",
    "Sans attendre la réponse, les deux hommes foncent sur Shu et lui ordonnent de ne plus bouger.",
    "Alors, Shu appuie sur la détente.",
    "La balle traverse la jambe du directeur. En hurlant, il confirme malgré lui que l'arme était bien réelle.",
    "Terrifiés, les deux gardes prennent immédiatement la fuite.",
    "Shu braque de nouveau le directeur : veut-il maintenant découvrir ce que fait une vraie balle ?",
    "L'homme supplie Shu et accuse soudain l'étudiante de l'avoir séduit.",
    "Il prétend qu'elle voulait obtenir une bourse et le titre d'élève modèle.",
    "En larmes, elle nie tout : elle préférerait conduire le camion de sa mère plutôt que fréquenter cette ordure.",
    "Le directeur rétorque que personne ne croira jamais la parole d'une fille pauvre.",
    "Mais Shu ne retient qu'un détail : un camion pourrait être très utile.",
    "Si cette fille sait réellement conduire, elle pourrait devenir une alliée précieuse.",
    "Il se tourne vers elle et lui propose de le suivre si elle veut survivre.",
    "Le directeur croit qu'ils vont prévenir la police. Il doit absolument les empêcher de partir.",
    "Il implore alors leur pardon, reconnaît une erreur et promet d'accepter toutes les conditions de Shu.",
    "Il offre une bourse, un emploi et pousse même l'ignominie jusqu'à proposer d'autres étudiantes.",
    "Mais intérieurement, il prépare déjà sa vengeance et compte tuer Shu dès qu'il sera libre.",
    "Shu lui répond de se détendre : il ne va ni le tuer, ni appeler la police.",
    "Le pistolet contre lui, Shu précise que la prison serait beaucoup trop confortable pour une ordure pareille.",
    "Soudain, une femme couverte de sang surgit dans le couloir en appelant désespérément à l'aide.",
    "Elle raconte que plusieurs élèves sont devenus fous et mordent tout le monde. Elle aussi vient d'être attaquée.",
    "Une morsure profonde est clairement visible sur son cou.",
    "Shu comprend que l'épidémie a déjà commencé dans l'école. Ils doivent partir immédiatement.",
    "Il attrape le bras de la jeune fille et lui ordonne de le suivre.",
    "Encore perdue, elle ne comprend absolument rien à la situation.",
    "Alors que la femme approche, Shu la met en joue et lui ordonne de rester loin d'eux.",
    "Ignorant le danger, un garde lui demande pourquoi il pointe une arme vers madame Hata.",
    "Shu tente de le prévenir, mais le garde comprend de travers.",
    "Il n'a plus le temps d'expliquer. Shu entraîne la jeune fille et se met à courir.",
    "Le garde s'approche naïvement de madame Hata et lui demande si elle va bien.",
    "Elle gémit, puis plante brutalement ses dents dans son cou sous ses cris d'horreur.",
    "Un hurlement retentit dans l'école : un zombie vient d'apparaître.",
    "Dans les couloirs, les élèves courent et hurlent à tout le monde de fuir.",
    "Tout près, un garçon infecté dévore déjà une victime qui le supplie de s'arrêter.",
    "Shu serre la main de la jeune fille et lui ordonne de rester derrière lui.",
    "Au milieu du chaos, un zombie leur fonce dessus. La fille hurle de terreur.",
    "Shu réagit aussitôt : une balle dans la tête abat la créature avant qu'elle ne les atteigne.",
    "Une notification apparaît alors : il vient d'éliminer un zombie de niveau un.",
    "Sa récompense est une capacité de pistolet : Tir précis, niveau un.",
    "Une fois équipée, cette capacité garantit qu'un tir sur quatre infligera un coup fatal à l'ennemi.",
    "Le système lui demande alors s'il souhaite l'équiper.",
    "Shu n'en croit pas sa chance.",
    "Dès son premier zombie, il vient déjà d'obtenir une capacité.",
    "Sans la moindre hésitation, il décide de l'équiper.",
    "Il ne reste que six balles, et Tir précis ne s'active que tous les quatre coups.",
    "Il devra donc viser intelligemment. Une lueur apparaît lorsqu'il équipe la capacité.",
    "Il tend ensuite une main à la jeune fille et lui demande si elle peut marcher.",
    "Encore terrifiée, elle demande son identité et ce qui arrive à l'école.",
    "Il se présente comme Shu Hura. Mais face à l'urgence, les longues explications devront attendre.",
    "Puis il lui demande son nom.",
    "Il répète sa question, plus fermement.",
    "Elle répond finalement : Ai Nakabayashi.",
    "Shu lui laisse deux choix : le suivre et survivre, ou rester ici et mourir.",
    "Pendant ce temps, sur le parking de l'école...",
    "Un homme grièvement blessé s'effondre contre un mur, couvert de sang.",
    "Il jure à son agresseur qu'il paiera pour ce qu'il vient de faire.",
    "Face à lui se tient un blond, une batte de baseball posée sur l'épaule.",
    "Le blond ricane : celui qui ne s'en sortira pas, c'est sa victime.",
    "Il avance et lui fracasse violemment la batte contre le crâne.",
    "Sous l'impact, l'homme crache du sang.",
    "Le blond éclate de rire : voilà trois ans qu'il supporte ses provocations.",
    "Sans la loi pour le retenir, il l'aurait battu à mort depuis bien longtemps.",
    "Un de ses amis l'interpelle soudain.",
    "Les filles populaires de leur classe se seraient réfugiées près de la piscine.",
    "Il propose donc d'aller les retrouver pour s'amuser.",
    "Après tout, ces filles se sont toujours crues supérieures aux autres.",
    "Aujourd'hui, il compte bien les faire ramper devant lui.",
    "Mais avant leur départ, une voix les interrompt.",
    "Elle affirme que ce type est toujours la même ordure.",
    "L'un des garçons reconnaît Shu et demande si c'est vraiment lui.",
    "Shu fait face au blond et à ses deux complices, Ai debout près de lui.",
    "Le blond se moque : Shu n'aurait donc rien appris après sa correction à l'infirmerie ?",
    "Tous les coups reçus ne lui ont visiblement pas suffi.",
    "Shu les prévient calmement : il ne le répétera qu'une seule fois.",
    "Qu'ils dégagent immédiatement... ou qu'ils meurent.",
    "Le blond éclate de rire, amusé de voir Shu jouer les durs devant lui.",
    "Il ordonne alors à son ami de lui donner une nouvelle leçon.",
    "L'autre accepte avec un sourire. Ce sera même un véritable plaisir.",
    "Sûr de lui, il s'approche de Shu et pose une main sur son épaule.",
    "Puis il lui demande s'il comprend seulement la situation dans laquelle il se trouve.",
    "Sans avertissement, Shu plante son couteau dans sa gorge et l'élimine en un instant.",
    "Le garçon n'a aucune chance. Son corps sans vie s'effondre lourdement au sol.",
    "Shu avance et les avertit : puisqu'ils sont si pressés de mourir...",
    "Qu'ils ne viennent surtout pas se plaindre de la suite.",
    "Le blond reste figé, incapable d'articuler le moindre mot.",
    "Puis il se reprend et hurle aux deux autres de réagir.",
    "Il leur ordonne de tuer Shu.",
    "Furieux, les deux garçons chargent en criant qu'il a tué leur ami.",
    "Ils jurent de le mettre en pièces.",
    "Derrière lui, Ai appelle Shu avec inquiétude.",
    "Il lui répond que tout est sous contrôle et qu'il terminera rapidement.",
    "Le premier garçon charge alors en hurlant : meurs !",
]


def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit("Usage: build_chatgpt_script.py PROJECT_ID")
    project_id = sys.argv[1]
    project_file = ROOT / "projects" / project_id / "project.json"
    project = json.loads(project_file.read_text(encoding="utf-8"))
    if len(project["segments"]) != len(TEXTS):
        raise RuntimeError(f"Le projet contient {len(project['segments'])} segments, mais le script ChatGPT en contient {len(TEXTS)}")
    payload = {"segments": [{"id": segment["id"], "rewritten_text": text} for segment, text in zip(project["segments"], TEXTS)]}
    output = project_file.parent / "script" / "chatgpt_styled_fr.json"
    output.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"ok": True, "segments": len(TEXTS), "output": str(output)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
